#!/bin/sh
# 
# $Id$
#
# Make a distribution tarball from a working copy.  Not very well
# written; all those rm -rfs might be dangerous.
# 
# See release notes and/or cvs logs entries for module history
# 
# -- Ed Avis, epa98@doc.ic.ac.uk
# 

vers=`perl -ne '/^XMLTV\s+([0-9.-]+)\s*$/ && (print("$1\n"), exit)' README`
dir="xmltv-$vers"
if test -e ../$dir; then echo $dir already exists; exit 1; fi
mkdir ../$dir      || exit 1
cp -avi * ../$dir  || exit 1
cd ../$dir         || exit 1
#find . -name CVS -type d -prune -exec rm -rf {} \; || exit 1
rm -rf attic       || exit 1
rm -rf leon        || exit 1
rm -rf cgi         || exit 1
rm -rf todo        || exit 1
rm -f mkdist       || exit 1
rm -f tvprefs      || exit 1
rm -f uk.xml       || exit 1
rm -f tv.xml       || exit 1
rm -f web_cache.db || exit 1
rm -f ChangeLog.old|| exit 1
echo ../$dir
echo 'You did remember to update the ChangeLog?'
