#!/usr/bin/perl -w
#
# tv_grep: filter out all programmes matching a regexp.  The channels
# are left unchanged.
#
# This is the first version, many features yet to implement!
#
use strict;
use XMLTV;
use Data::Dumper;

my $pattern = shift;
die 'usage: $0 pattern [filename]' if not defined $pattern;

my $filename = @ARGV ? $ARGV[0] : '-';
my ($encoding, $credits, $ch, $progs) = @{XMLTV::read_data($filename)};
@$progs = grep { (my $tmp = Dumper($_)) =~ /$pattern/o } @$progs;
XMLTV::write_data([$encoding, $credits, $ch, $progs]);
